#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

if [ -x "$HOME/.local" ] ; then
  source "$HOME/.local"
fi

fpath=($fpath $HOME/.zsh-git/functions)

# Use ~/cache as default working directory
cdpath=( ~/cache )
cd ~/cache

