#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

if [ -x "$HOME/.local" ] ; then
  source "$HOME/.local"
fi

fpath=($fpath $HOME/.zsh-git/functions)

# Use ~/cache as default working directory
cdpath=( ~/cache )
cd ~/cache

export EMAIL="mail@michaelbarton.me.uk"
export FULLNAME="Michael Barton"

export GIT_AUTHOR_NAME=$FULLNAME
export GIT_COMMITTER_NAME=$FULLNAME
export GIT_AUTHOR_EMAIL=$EMAIL
export GIT_COMMITTER_EMAIL=$EMAIL

export PAGER='less'
export LESS='-R -M --shift 5'
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s"

# language
LC_ALL='en_GB.UTF-8'
LANG='en_GB.UTF-8'
LC_CTYPE=C
DISPLAY=:0

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
