#!/bin/zsh

if [ "$OSTYPE" = "darwin10.0" ] ; then

  # Show specified file in finder
  function show(){open -R "$@"}
  
  # Open file in numbers
  function numbers(){open -a /Applications/iWork\ \'09/Numbers.app "$@"}

fi
