#!/bin/zsh

alias SS=SEQQC-

# JGI jira
alias j='jira --user=mbarton --password=`get-pass jgi.jira` --server=https://issues.jgi-psf.org/'

function jc(){
  if [ -z "$1" ]                           # Is parameter #1 zero length?
  then
    echo "JIRA issue ID required"
  else
    file=`mktemp`
    vim -c "set ft=txt" --nofork $file
    j --action=addComment --issue=$1 --file=$file
  fi
}

