#!/bin/zsh

# Clone specified repo and switch to latest commit branch
function gime () {
  repo=$1
  if [ -z "$2" ]
  then
     dest=$1
  else
     dest=$2
  fi
  git clone -p ${repo} ${dest}
  cd ${dest}

  git checkout -b develop origin/develop

  commit=`git recent`
  remote=`git which ${commit} | tr -d ' '`
  branch=`echo ${remote} | cut -d / -f 3,4`
  git checkout -b ${branch} ${remote}

  cp ~/.dotfiles/examples/autotest .autotest
  cp ~/.dotfiles/examples/rspec .rspec
}
