#!/bin/bash

export ORACLE_HOME=/usr/local/Cellar/oracle/11_2

export LOG=~/Dropbox/personal/daily.log

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre"
export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.7.1.0/libexec"

export GITHUB_TOKEN=`get-pass github.token`
export HOMEBREW_GITHUB_API_TOKEN=$GITHUB_TOKEN

eval "$(docker-machine env default)"
