#!/bin/zsh

alias zen='~/.zen'
alias cache='~/cache'

# Shortcut to aspell that sorts dictionary afterwards
function sp(){aspell -c "$@" && ~/.dotfiles/bin/sort_dictionary}

# Make git github aware
function git(){hub "$@"}

# These have to be functions because ls is aliased to coreutils gls
function lls(){ls -l --color=auto $@}
function lst(){ls -ltr --color=auto $@}
function ls(){ls --color=auto $@}
