#!/bin/bash

alias zen='~/.zen'
alias cache='~/cache'
alias cellar='/usr/local/Cellar'

# Shortcut to aspell that sorts dictionary afterwards
function sp(){aspell -c "$@" && ~/.dotfiles/bin/sort_dictionary}

# Make git github aware
function git(){hub "$@"}
