#!/bin/zsh

alias zen='cd ~/.zen'
alias cache='cd ~/cache'
alias cellar='cd /usr/local/Cellar'

# Shortcut to aspell that sorts dictionary afterwards
function sp(){aspell -c "$@" && ~/.dotfiles/bin/sort_dictionary}

# Make git github aware
function git(){hub "$@"}
