#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

# Global aliases
alias -g X='| xargs'
alias -g XX='| xargs -I {}'
alias -g X0='| xargs -0'
alias -g XX0='| xargs -0 -I {}'

# Suffix based aliases
alias -s gz=gunzip
alias -s bz2=bunzip2
alias -s zip=unzip
alias -s tar.gz='tar xzf'
alias -s tgz='tar xzf'
alias -s tar.bz2='tar xjf'

alias -s rb='ruby -rubygems'
alias -s py=python

# Avoid spelling corrections on certain commands
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
