#!/bin/zsh

within-bundled-project()
{
    local dir="$(pwd)"
    while [ "$(dirname $dir)" != "/" ]; do
        [ -f "$dir/Gemfile" ] && return
        dir="$(dirname $dir)"
    done
    false
}

run-with-bundler()
{
    if within-bundled-project; then
        bundle exec $@
    else
        $@
    fi
}

bundled_commands=(
cap
capify
cucumber
foreman
guard
haml
heroku
html2haml
rackup
rails
rake
rake2thor
rspec
ruby
sass
sass-convert
serve
shotgun
spec
spork
thin
thor
tilt
tt
turn
unicorn
unicorn_rails)

for i in $bundled_commands; do
  alias $i="run-with-bundler $i"
done
