brew "actionlint"
brew "ansible-lint"
brew "aom"
brew "aspell"
brew "atuin"
brew "aws-iam-authenticator"
brew "bash"
brew "bat"
brew "bzip2"
brew "cmake"
brew "coreutils"
brew "difftastic"
brew "docker", link: false
brew "docker-compose"
brew "dockutil", link: false
brew "duckdb"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "geckodriver"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "glow"
brew "gnu-sed"
brew "grafana"
brew "groovy"
brew "htop"
brew "jpeg-xl"
brew "jq"
brew "just"
brew "kubernetes-cli"
brew "lazygit"
brew "leveldb"
brew "libass"
brew "libmagic"
brew "libpq"
brew "mise"
brew "mutt"
brew "neovim"
brew "offlineimap"
brew "ollama"
brew "openjdk@17"
brew "openssl@1.1"
brew "openvino"
brew "pandoc"
brew "parallel"
brew "pigz"
brew "pipx"
brew "pixz"
brew "pngcrush"
brew "postgresql@14"
brew "prettierd"
brew "procs"
brew "psgrep"
brew "python@3.10"
brew "python@3.11"
brew "r"
brew "rclone"
brew "ripgrep"
brew "srt"
brew "starship"
brew "subversion"
brew "tmux"
brew "trash", link: true
brew "tree"
brew "unbound"
brew "urlview"
brew "uv"
brew "w3m"
brew "xmlstarlet"
brew "yazi"
brew "youplot"
brew "zlib"
brew "zopfli"
brew "zoxide"

cask "amethyst"
cask "db-browser-for-sqlite"
cask "docker-desktop", args: { appdir: "/Applications" }
cask "dockutil"
cask "font-fira-code", args: { appdir: "/Applications" }
cask "font-fira-code-nerd-font", args: { appdir: "/Applications" }
cask "font-fira-mono", args: { appdir: "/Applications" }
cask "font-fira-mono-for-powerline", args: { appdir: "/Applications" }
cask "font-fira-mono-nerd-font", args: { appdir: "/Applications" }
cask "font-fira-sans", args: { appdir: "/Applications" }
cask "font-fira-sans-condensed", args: { appdir: "/Applications" }
cask "font-fira-sans-extra-condensed", args: { appdir: "/Applications" }
cask "font-inconsolata-dz-for-powerline", args: { appdir: "/Applications" }
cask "font-raleway", args: { appdir: "/Applications" }
cask "ghostty"
cask "hammerspoon"
cask "iterm2", args: { appdir: "/Applications" }
cask "mactex"
cask "pycharm-ce", args: { appdir: "/Applications" }
cask "quarto"
cask "rectangle", args: { appdir: "/Applications" }
cask "signal", args: { appdir: "/Applications" }
cask "spotify"
cask "sublime-text"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-containers"
vscode "anysphere.remote-ssh"
vscode "charliermarsh.ruff"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "mtxr.sqltools"
vscode "quarto.quarto"
vscode "tomoki1207.pdf"
vscode "vscodevim.vim"
npm "@anthropic-ai/claude-code"
npm "prettier"
npm "typescript"
