#!/bin/zsh

autoload -U is-at-least

autoload -U edit-command-line
zle -N edit-command-line

# Autoload zsh modules when they are referenced
zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

unsetopt BG_NICE		# do NOT nice bg commands

setopt ALL_EXPORT

# Case insensitive globbing
setopt extendedglob
unsetopt CASE_GLOB

setopt CORRECT	            # command CORRECTION
setopt NO_MENU_COMPLETE     # no menu completion of commands
setopt LIST_AMBIGUOUS       # unambiguous prefix completion is done silently
setopt NO_LIST_BEEP         # don't beep for completion
setopt LIST_PACKED          # different width for completion
setopt NO_LIST_ROWS_FIRST   # sort by colums
setopt LIST_TYPES

# Set/unset  shell options
setopt   notify globdots correct pushdtohome cdablevars autolist
setopt   correctall autocd recexact longlistjobs
setopt   autoresume histignoredups pushdsilent noclobber
setopt   autopushd pushdminus extendedglob rcquotes mailwarning
unsetopt bgnice autoparamslash
