#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

if [ -x "$HOME/.local" ] ; then
  source "$HOME/.local"
fi

[[ -s "/Users/mike/.rvm/scripts/rvm" ]] && source "/Users/mike/.rvm/scripts/rvm"

cdpath=( ~ ~/cache )

export GEM_HOME="`echo $HOME`/.gem"

export PATH=~/.bin:$GEM_HOME/bin:/usr/local/bin:$PATH

export EMAIL="mail@michaelbarton.me.uk"
export FULLNAME="Michael Barton"

export GIT_AUTHOR_NAME=$FULLNAME
export GIT_COMMITTER_NAME=$FULLNAME
export GIT_AUTHOR_EMAIL=$EMAIL
export GIT_COMMITTER_EMAIL=$EMAIL

export GITHUB_TOKEN=`get-pass github.token`

export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home/"

export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export PAGER='less'
export LESS='-R -M --shift 5'
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s"

if [ -d  $HOME/.ec2 ] ; then
  export EC2_HOME=~/.ec2
  export EC2_PRIVATE_KEY="$(/bin/ls $EC2_HOME/pk-*.pem)"
  export EC2_CERT="$(/bin/ls $EC2_HOME/cert-*.pem)"
fi

# history
HISTFILE=$HOME/.zhistory
HISTSIZE=1000
SAVEHIST=1000

# language
LC_ALL='en_GB.UTF-8'
LANG='en_GB.UTF-8'
LC_CTYPE=C
DISPLAY=:0

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
