#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

# Suffix based aliases
alias -s tar.gz='tar xzf'
alias -s tgz='tar xzf'
alias -s tar.bz2='tar xjf'
alias -s gz=gunzip
alias -s bz2=bunzip2
alias -s zip=unzip

alias -s rb='ruby -rubygems'
alias -s py=python

# Avoid spelling corrections on certain commands
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'

# Shortcut to aspell that sorts dictionary afterwards
function sp(){aspell -c "$@" && ~/.dotfiles/bin/sort_dictionary}

# Make git github aware
function git(){hub "$@"}

# Git shortcuts
alias gl='git log --decorate --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias gc='git commit'
alias gca='git commit -a'
alias ga='git add'
alias gap='git add --patch'
alias gd='git diff'
alias gdt='git diff --word-diff'
alias gs='git status -sb'
alias gsw='git checkout'
alias gb='git branch'
alias grm='git rm'
alias gr='git rebase'
alias gri='git rebase --interactive'
alias gsvn='git svn'

alias ls='ls -G'
alias lls='ls -l'
alias lst='ls -ltr'

# Vim instead of vi
alias vi='vim'

# Quiet R
alias R='R --quiet --no-save --no-restore' 

# Print grep results in color
alias grep='grep --color=auto'
