#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

# Git shortcuts
alias gl='git log --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias gc='git commit'
alias gca='git commit -a'
alias ga='git add'
alias gap='git add --patch'
alias gd='git diff'
alias gs='git status'
alias gsw='git checkout'
alias gb='git branch'
alias grm='git rm'
alias gr='git rebase'
alias gri='git rebase --interactive'
alias gsvn='git svn'

alias ls='ls --color=auto'
alias lls='ls -l'

# Vim instead of vi
alias vi='vim'

# Quiet R
alias R='R --quiet --no-save --no-restore' 

# Sort process list by ram usage
alias top='top -o rsize'

# Three lines of context, and always add filename
alias grep='grep --color=auto'

alias sp='aspell -c'
