#!/bin/zsh

if [[ -x `which git` ]]; then
	function git-branch-name () {
		git branch 2> /dev/null | grep '^\*' | sed 's/^\*\ //'
	}
	function git-dirty () {
		git status 2> /dev/null | grep "nothing to commit (working directory clean)"
		echo $?
	}
	# git: Fetch origin changes, rebase current branch changes onto master, push to origin
	function grc () {
		branch=$(git-branch-name) 
		git fetch origin master && \
		git rebase origin/master && \
		git checkout master && \
		git rebase "${branch}" && \
		git push origin master && \
		git checkout "${branch}" && \
		git rebase master
        }

	# svn: Rebases current changes onto master, and pushes to repository
	function gsdc () {
		branch=$(git-branch-name) 
		git checkout master && \
		git rebase "${branch}" && \
		git svn rebase && \
		git svn dcommit && \
		git checkout "${branch}" && \
		git rebase master
	}
        function git-need-to-push() {
        if [[ -z $(git status | grep 'Your branch is ahead' 2> /dev/null); ]] then
	else
          echo "↑ "
        fi
        }
	function git-scoreboard () {
		git log | grep '^Author' | sort | uniq -ci | sort -r
	}
	function git-track () {
		branch=$(git-branch-name)
		git config branch.$branch.remote origin
		git config branch.$branch.merge refs/heads/$branch
		echo "tracking origin/$tracking"
	}
	function github-init () {
		git config branch.$(git-branch-name).remote origin
		git config branch.$(git-branch-name).merge refs/heads/$(git-branch-name)
	}
	
	function github-url () {
		git config remote.origin.url | sed -En 's/git(@|:\/\/)github.com(:|\/)(.+)\/(.+).git/https:\/\/github.com\/\3\/\4/p'
	}
	
	# Seems to be the best OS X jump-to-github alias from http://tinyurl.com/2mtncf
	function github-go () {
		open $(github-url)
	}
	
	function nhgk () {
		nohup gitk --all &
	}
fi
