#!/bin/zsh

function git-dirty() {
  git update-index -q --refresh; git diff-index --quiet --cached HEAD --ignore-submodules -- && git diff-files --quiet --ignore-submodules
  echo $?
}

# Clone specified repo and switch to latest commit branch
function gime () {
  repo=$1
  if [ -z "$2" ]
  then
     dest=$1
  else
     dest=$2
  fi
  git clone -p ${repo} ${dest}
  cd ${dest}

  commit=`git recent`
  remote=`git which ${commit} | tr -d ' '`
  branch=`echo ${remote} | cut -d / -f 3,4`
  git checkout -b ${branch} ${remote}

  cp ~/.dotfiles/examples/autotest .autotest
}
