#!/bin/zsh

function git-branch-name() {
  git branch --no-color 2>| /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/' 
}

function git-dirty() {
  git update-index -q --refresh; git diff-index --quiet --cached HEAD --ignore-submodules -- && git diff-files --quiet --ignore-submodules
  echo $?
}

# git: Fetch origin changes, rebase current branch changes onto master, push to origin
function gsync () {
        branch=$(git-branch-name)
        git pull --rebase origin master && \
        git rebase origin/master && \
        git checkout master && \
        git rebase "${branch}" && \
        git push origin master && \
        git checkout "${branch}" && \
        git rebase master
}

# svn: Rebases current changes onto master, and pushes to repository
function gsdc () {
        branch=$(git-branch-name)
        git checkout master && \
        git rebase "${branch}" && \
        git svn rebase && \
        git svn dcommit && \
        git checkout "${branch}" && \
        git rebase master
}
