#!/bin/zsh

setopt prompt_subst
autoload colors
colors

reset="%{%b%s%u$reset_color%}"
arrow="%{$fg_bold[red]%} ➜  "
current_directory="%{$fg_bold[cyan]%c%}"
end=" %%%% "

function git-prompt() {
  branch=$(git-branch-name)
  
  if [[ -z $branch ]]; then
    echo ""
  else
    if [[ $(git-dirty) = 1 ]]; then
      dirty_color=$fg_bold[red]
    else
      dirty_color=$fg[green]
    fi
    push=$(git-need-to-push)
    echo "%{$fg_bold[blue]%} (%{$dirty_color%}$branch%{$reset_color%}%{$push%}%{$fg_bold[blue]%})"
  fi
}

PROMPT='\
$reset\
$arrow\
$reset\
$current_directory\
$reset\
$(git-prompt)\
$reset\
$end'
