#!/bin/zsh

setopt prompt_subst
autoload colors
colors

reset="%{%b%s%u$reset_color%}"
current_directory="{ %{$fg[cyan]%c$reset%} }"
end=" %%%% "

function git-prompt() {
  branch=$(git-branch-name)
  
  if [[ -z $branch ]]; then
    echo ""
  else
    if [[ $(git-dirty) = 1 ]]; then
      dirty_color=$fg[red]
    else
      dirty_color=$fg[green]
    fi
    push=$(git-need-to-push)
    echo "-( %{$dirty_color%}$branch%{$reset_color%} %{$push%})"
  fi
}

PROMPT='\
$reset\
$current_directory\
$(git-prompt)\
$end'
