#!/bin/bash

alias af='./script/autofeature'
alias at='./script/autotest'

alias dot='cd ~/.dotfiles'

# Git shortcut
alias g='git'

# Personal log
alias log='add_log_entry'

# These have to be functions because ls is aliased to coreutils gls
alias lls='ls -l --color=auto'
alias lst='ls -ltr --color=auto'

# Vim instead of vi
alias vi='vim'

# Quiet R
alias R='R --quiet --no-save --no-restore'

# Quiet octave
alias octave='octave --quiet'

# Print grep results in color
alias grep='grep --color=auto'
