#!/bin/bash

alias af='./script/autofeature'
alias at='./script/autotest'

alias dot='cd ~/.dotfiles'

# Git shortcut
alias g='git'

# These have to be functions because ls is aliased to coreutils gls
function lls {
  ls -l --color=auto $@
}
function lst {
  ls -ltr --color=auto $@
}


alias vim='vim -w ~/.vim/log "$@"'

# Vim instead of vi
alias vi='vim'

# Quiet R
alias R='R --quiet --no-save --no-restore'

# Quiet octave
alias octave='octave --quiet'

# Print grep results in color
alias grep='grep --color=auto'
