#!/bin/bash

# Vim in full screen mode
alias dvim='gvim +"call ToggleWindowSize()"'

alias dot='~/.dotfiles'

# Git shortcut
alias g='git'

# Vim instead of vi
alias vi='vim'

# Quiet R
alias R='R --quiet --no-save --no-restore'

# Quiet octave
alias octave='octave --quiet'

# Print grep results in color
alias grep='grep --color=auto'

alias sc='starcluster'
