#!/bin/bash

alias dot='cd ~/.dotfiles'
alias g='git'

# These have to be functions because ls is aliased to coreutils gls
alias lls='ls -l --color=auto'
alias lst='ls -ltr --color=auto'

# neovim instead of vi/nvim
alias vi='nvim'
alias vim='nvim'

# bat instead of cat
alias cat='bat'

# fd instead of find
alias find='fd'

# Quiet R
alias R='R --quiet --no-save --no-restore'

# Quiet octave
alias octave='octave --quiet'

# Print grep results in color
alias grep='grep --color=auto'
