#!/bin/sh
# Reorders the dictionary in the way aspell likes it.

TMP=~/aspell.en.pws.tmp
ORIG=~/.dotfiles/aspell/aspell.en.pws
HEADER=personal_ws

grep $HEADER $ORIG | sed 's/ $//' > $TMP
grep -v $HEADER $ORIG | sort -f >> $TMP
mv $TMP $ORIG
