#!/bin/bash

set -e

JIRA="jira --user=mbarton --password=`get-pass jgi.jira` --server=https://issues.jgi-psf.org/"

if [ -z "$1" ]; then
    echo "JIRA issue ID required" 1>&2
    exit 1
fi


FILE=`/usr/local/bin/gmktemp`
$JIRA --action=getFieldValue --issue=$1 --field=description | tail +2 > $FILE

vim -c "set ft=mail" --nofork $FILE

if [[ -z `cat $FILE` ]]; then
    echo "Aborting on empty comment message." 1>&2
    exit 1
fi

$JIRA --action=setFieldValue --issue=$1 --field=description --file=$FILE
