---
- name: Link dotfiles
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    state: link
  loop:
    # Dictionary
    - { src: "aspell/aspell.en.pws", dest: ".aspell.en.pws" }
    - { src: "aspell/aspell.conf", dest: ".aspell.conf" }
    - { src: "aspell/sort_dictionary", dest: ".bin/sort_dictionary" }

    # Shell
    - { src: "bash/bashrc", dest: ".bashrc" }
    - { src: "inputrc", dest: ".inputrc" }
    - { src: "fish/config.fish", dest: ".config/fish/config.fish" }
    - { src: "fish/fish_plugins", dest: ".config/fish/fish_plugins" }
    - {
        src: "fish/completions/fish_gh_completion.fish",
        dest: ".config/fish/fish_gh_completion",
      }

    # Scripts for working with data
    - { src: "parquet/csv_to_parquet.py", dest: ".bin/csv_to_parquet" }
    - { src: "parquet/parquet_to_csv.py", dest: ".bin/parquet_to_csv" }
    - { src: "yml/format_yml.py", dest: ".bin/format_yml" }

    # Misc. scripts and config
    - { src: "zettel/today.sh", dest: ".bin/today" }
    - { src: "git/gitconfig", dest: ".gitconfig" }
    - { src: "markdown/md2docx.sh", dest: ".bin/md2docx" }
    - {
        src: "poetry/update_poetry_dependencies.py",
        dest: ".bin/update_poetry_dependencies",
      }
    - { src: "github/create_pr.bash", dest: ".bin/pr" }
    - { src: "hammerspoon/init.lua", dest: ".hammerspoon/init.lua" }
    - { src: "ghostty/config", dest: ".config/ghostty/config" }
    - {
        src: "python/scratch_python_project.sh",
        dest: ".bin/scratch_python_project",
      }
