---
- name: link dotfiles
  file:
    src: "~/.dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    state: link
  loop:
    - { src: "tmux/tmux.conf", dest: ".tmux.conf"}
    - { src: "git/gitconfig", dest: ".gitconfig"}
    - { src: "muttrc", dest: ".muttrc"}
    - { src: "mutt", dest: ".mutt"}

    # Dictionary
    - { src: "aspell/aspell.en.pws", dest: ".aspell.en.pws"}
    - { src: "aspell/aspell.conf", dest: ".aspell.conf"}
    - { src: "aspell/sort_dictionary", dest: ".bin/sort_dictionary"}

    # Shell
    - { src: "bash/bashrc", dest: ".bashrc"}
    - { src: "inputrc", dest: ".inputrc"}
    - { src: "fish/config.fish", dest: ".config/fish/config.fish"}
    - { src: "fish/fish_plugins", dest: ".config/fish/fish_plugins"}
    - { src: "fish/completions/fish_gh_completion.fish", dest: ".config/fish/fish_gh_completion"}

    # Vim
    - { src: "nvim/init.vim", dest: ".config/nvim/init.vim"}
    - { src: "vim/ftplugin/markdown.vim", dest: ".config/nvim/ftplugin/markdown.vim"}

    # Scripts for working with data
    - { src: "parquet/csv_to_parquet.py", dest: ".bin/csv_to_parquet"}
    - { src: "parquet/parquet_to_csv.py", dest: ".bin/parquet_to_csv"}
    - { src: "parquet/parquet_less.sh", dest: ".bin/parquet_less"}
    - { src: "yml/format_yml.py", dest: ".bin/format_yml"}

    # Vimwiki scripts
    - { src: "zettel/process_today.sh", dest: ".bin/process_today"}
    - { src: "zettel/today.sh", dest: ".bin/today"}
    - { src: "zettel/generate_article_record.py", dest: ".bin/generate_article_record"}

    # Scripts
    - { src: "ansible/apply_ansible", dest: ".bin/apply_ansible"}
    - { src: "ncbi/fetch_fasta_gene.sh", dest: ".bin/fetch_fasta_gene"}
    - { src: "ncbi/fetch_genbank.sh", dest: ".bin/fetch_genbank"}
    - { src: "markdown/md2docx.sh", dest: ".bin/md2docx"}
    - { src: "poetry/update_poetry_dependencies.py", dest: ".bin/update_poetry_dependencies"}



