#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "No directory supplied."
  exit 1
fi

export SSH_AUTH_SOCK=`find /tmp/launch-*/Listeners -user $1 -type s | head -1`

directory=$1

cd $directory
ahead=`git rev-list origin..HEAD`
behind=`git rev-list HEAD..origin`

if [ ! -z "$behind" ]; then
 echo "Unable to push, $directory HEAD is behind origin."
 exit 0
fi

if [ ! -z "$ahead" ]; then
 echo "Pushing $directory to origin."
  git push origin master 2> ~/.logs/push_directory.log
 exit 0
fi

