# Launch Jupyter Notebook
notebook:
    uv run jupyter notebook notebooks/

# Format and lint the code using ruff
fmt:
    uv run ruff format .
    uv run ruff check --fix .

# Run the tests using pytest
test:
    uv run pytest tests/

# Run the main script
run:
    uv run python {{ cookiecutter.package_name }}/main.py
