#!/bin/bash

cd ~/.dotfiles
ahead=`git rev-list origin..HEAD`
behind=`git rev-list HEAD..origin`


if [ ! -z $ahead ]; then
  msg="AHEAD"
fi

if [ ! -z $behind ]; then
  msg="$msg BEHIND"
fi

if [ ! -z $msg ]; then
  echo "Dotfiles $msg |"
fi
