#!/bin/bash

cd ~/.dotfiles
ahead=`git rev-list origin..HEAD`
behind=`git rev-list HEAD..origin`

if [ ! -z "$ahead" ]; then
 echo "AHEAD:`echo $ahead | wc -l | tr -d ' '`"
fi

if [ ! -z "$behind" ]; then
 echo "BEHIND:`echo $behind | wc -l | tr -d ' '`"
fi
