#!/bin/bash

$running=`~/.jgi_bin/uge_queue | cut -f 2 -d ' ' | grep r`
$waiting=`~/.jgi_bin/uge_queue | cut -f 2 -d ' ' | grep q`

if [ ! -z "$running" ]; then
  echo "Running:`echo $running | wc -l | tr -d ' '`"
fi

if [ ! -z "$waiting" ]; then
  echo "Behind:`echo $waiting | wc -l | tr -d ' '`"
fi
