#!/bin/zsh

alias cache='cd ~/cache'
alias cellar='cd /usr/local/Cellar'

# Shortcut to aspell that sorts dictionary afterwards
function sp(){aspell -c "$@" && ~/.dotfiles/bin/sort_dictionary}

# Make git github aware
function git(){hub "$@"}

# Tmux
function tkw { tmux kill-window -t $1 }
function tks { tmux kill-session -t $1 && tmux list-session}
function tss { tmux switch-client -t $1 }
function tls { tmux list-session }
