name: Formatting checks

on:
  push:
  pull_request:

env:
  TERM: xterm

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check formatting
        run: make fmt_check
